#!/bin/bash
--text="Introduce un nombre de archivo"\
--add-entry="v1"\
if [ -r $v1 ]
then 
zenity --info --text="$v1 es legible"
fi
if [ -w $v1 ]
then 
zenity --info --text="$v1 es grabable"
fi
if [ -x $v1 ]
then
zenity --info --text="$v1 es ejecutable"
echo ""
fi

