#!/bin/bash


#####
if [ ! -d $HOME/bin ]
then
  mkdir $HOME/bin
fi
#
N=0          
for ARCH in *
do
  if [ -x $ARCH -a -f $ARCH ]  # ejecutable y archivo común (no directorio)
  then
    cp $ARCH $HOME/bin
   echo "  $ARCH fue copiado a $HOME/bin"
    N=`expr $N + 1`
  fi
done
if [ $N -eq 0 ]
then
  echo "No se copió ningún archivo"
else
  echo "Fueron copiados $N archivos"
fi
