#!/bin/bash

if [ ! -d $1 ]
then
  echo Error: ligas: $1 no es un directorio
  exit
fi
echo Archivos que son enlace simbólico:
ls -l | grep "^l" | cut -56 -
echo

echo Archivos que tienen enlace hard:
ls -l | grep -v "^d" | cut -c11 - | grep -v "^ 1" | cut -c46 -
